### ISSUE TITLE
Linux Mint -  rocm-gdb5.2.3,  rocm-lvm5.2.3 : Depends but is not installable

### ISSUE THREAD

**Issue by zDEFz** [srinivamd/rocminstaller#2]
Upon following your guide, I had the following problems

$ sudo python3 ./rocminstall.py --rev 5.2.3

tried

sudo add-apt-repository --yes ppa:deadsnakes/ppa && \
sudo apt-get update && \
sudo apt install --yes python3.8

```The following packages have unmet dependencies:
 rocm-gdb5.2.3 : Depends: libpython3.8 but it is not installable
 rocm-llvm5.2.3 : Depends: python but it is not installable
                  Depends: libstdc++-5-dev but it is not installable or
                           libstdc++-7-dev but it is not installable
                  Depends: libgcc-5-dev but it is not installable or
                           libgcc-7-dev but it is not installable
                  Recommends: gcc-multilib but it is not going to be installed
                  Recommends: g++-multilib but it is not going to be installed
E: Unable to correct problems, you have held broken packages.```

**Comment by zDEFz** [comment]
No luck
https://github.com/RadeonOpenCompute/ROCm/issues/1713#issuecomment-1172883476
https://github.com/RadeonOpenCompute/ROCm/issues/1713#issuecomment-1193332549

https://github.com/novaspirit/amdgpu-rocm-ubu22 -> debs are currently broken

**Comment by srinivamd** [comment]
@zDEFz is this still an issue? Sorry I missed this.

**Comment by zDEFz** [comment]
> @zDEFz is this still an issue? Sorry I missed this.

Ended up using a rocm docker container

**Comment by srinivamd** [comment]
Ok. We use the script to install ROCm after following the pre-install steps documented in the README. Thanks for the update @zDEFz 
Will close this issue.
